version: "3.9"

services:
  miminet:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: miminet
    depends_on:
      rabbitmq:
        condition: service_healthy
        required: false
    restart: always
    networks:
      - rabbitmq_network
      - miminet_network
    env_file:
      - .env
    expose:
      - 80
    volumes:
      - databases:/app/instance
      - ./src/static/images:/app/static/images
      - ./src/static/svg:/app/static/svg
      - ./src/static/avatar:/app/static/avatar
      - ./src/static/video:/app/static/video
      - ./src/static/pcaps:/app/static/pcaps
      - ./src/static/assets:/app/static/assets
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    volumes:
      - ./default.conf.template:/etc/nginx/templates/default.conf.template
      - ./letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    networks:
      - miminet_network

volumes:
  databases:

networks:
  miminet_network:
    driver: bridge
  rabbitmq_network:
    name: rabbitmq_network
    external: true