name: Full test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Start frontend
        run: |
          cd front/
          sed -i 's/MODE=prod/MODE=dev/' .env
          docker compose up -d

      - name: Start selenium
        run: |
          cd front/tests/docker
          docker compose up -d

      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: "3.12.3"

      - name: Install dependencies
        run: |
          sudo python -m pip install pip pytest selenium --ignore-installed urllib3
          sudo python -m pip install -r front/requirements.txt --ignore-installed

      - name: Check availability
        run: |
          docker ps
          curl -f localhost

      - name: Run tests
        run: |
          sudo python3 -m pytest -vv -s front/tests
