name: Full test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Disable packet transmission to filters
        run: |
          sudo sysctl -w net.bridge.bridge-nf-call-iptables=0
          sudo sysctl -w net.bridge.bridge-nf-call-arptables=0
          sudo sysctl -w net.bridge.bridge-nf-call-ip6tables=0
          sudo sysctl -p

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v1

      - name: Start frontend
        run: |
          cd front/
          sed -i 's/MODE=prod/MODE=dev/' .env
          docker compose up -d

      - name: Start backend
        run: |
          cd back/
          docker compose up -d
    
      - name: Start selenium
        run: |
           cd front/tests/docker
           docker compose up -d

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          sudo python3 -m pip install pytest
          sudo python3 -m pip install selenium

      - name: Wait for services to start
        run: sleep 30

      - name: Check Docker logs
        run: |
          docker logs miminet
          docker logs nginx

      - name: Check availability
        run: |
          docker ps
          curl -f localhost

      - name: Run tests
        run: |
           sudo python3 -m pytest -vv -s front/tests